version: "3"
services:
 mymongodb:
   image: mongo
   container_name: "mymongodb"
   ports:
     - 27017:27017
 springboot-mongodb:
   image: xmeme
   container_name: springboot-mongodb
   ports:
     - 8080:8080
   links:
      - mymongodb